import { type NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";
import ReactMarkdown from "react-markdown";
import { api } from "~/utils/api";

const ChatPage: NextPage = () => {
  //Get chat id from url path (nextjs)
  const { query, replace } = useRouter();
  const chatId = query.chatId as string;

  const utils = api.useContext();
  const session = useSession();
  const [input, setInput] = useState("");

  const {
    data: chat,
    isLoading: isLoadingMessages,
    isError,
    refetch: refetchMessages,
  } = api.message.getAll.useQuery(
    { chatId },
    {
      onError: () => {
        console.log("on error");
        void replace("/");
      },
    }
  );

  const { mutate: submitMessage, isLoading: isCreatingMessage } =
    api.openai.createChatCompletion.useMutation({
      onSuccess: () => {
        setInput("");
        void refetchMessages();
      },
    });

  const { mutate: deleteChat } = api.chat.delete.useMutation({
    onSettled: async () => {
      await replace("/");
      void utils.chat.getAll.invalidate();
    },
  });

  if (!session) {
    return null;
  }

  if (isError) {
    return <div>error loading messages</div>;
  }

  if (!chat && isLoadingMessages) {
    return <div className="loading btn-ghost btn p-5" />;
  }

  return (
    <>
      <Head>
        <title>Chat {chatId}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex  max-h-screen w-full flex-col p-5">
        <h1 className="text-xl font-bold">{chat.name}</h1>

        <div className="grow overflow-y-scroll">
          {chat.messages.map((message) => (
            <div className="p-4" key={message.id}>
              <p className="font-bold">{message.role}</p>
              <span className="prose">
                <ReactMarkdown>{message.content}</ReactMarkdown>
              </span>
            </div>
          ))}
        </div>

        <form
          onSubmit={(e) => {
            e.preventDefault();
            if (!chatId) return;
            void submitMessage({
              chatId,
              message: input,
            });
          }}
          className="form-control flex flex-row gap-4"
        >
          <input
            type="text"
            className="input-bordered input w-full"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            disabled={isCreatingMessage}
          />
          <button
            disabled={isCreatingMessage}
            className={`btn-outline ${isCreatingMessage ? "loading" : ""} btn`}
            type="submit"
          >
            send
          </button>
          <button
            onClick={(e) => {
              e.preventDefault();
              if (!chatId) return;
              void deleteChat({ chatId });
            }}
            className="btn-error btn"
            disabled={isCreatingMessage}
          >
            Delete Chat
          </button>
        </form>
      </div>
    </>
  );
};

export default ChatPage;
